GET http://localhost:8080

### Send POST request with json body
POST http://localhost:8080
Content-Type: application/json

{
  "id": 999,
  "value": "content"
}

### Send POST request with json body
POST http://localhost:8080/postTest
Content-Type: application/json

{
  "id": 1,
  "value": "felipe",
  "number": 3.14
}

###
POST http://localhost:8080/s3
Content-Type: application/json

{
  "bucketName": "b1"
}

###
GET http://localhost:8080/s3
